@startuml

'left to right direction
together {
component [Kafka\nCli] as kafCli
component [Site  Tracking\nTraffice simulator] as traffic
}

package "Aerospike" {
() "Aerospike\nClient" as asClient
component [Aerospike\nEnterprise\nEdition] as asee
asClient - asee

() "Outbound\nKafka" as asOutbound
component [Aerospike\nOutbound Kafka\nConnector] as asKafka
asOutbound - asKafka
}
package "Kafka and Zookeeper" {
() "Kafka\nclient" as kafClient
component [Kafka\nCluster] as kafCluster
kafClient - kafCluster

component [Zoo\nKeeper] as zookeeper
}

traffic --> asClient

asee --> asOutbound
zookeeper <..> kafCluster

asKafka -r-> kafClient

kafCli --> kafClient
@enduml